---
title: "Import"
author: "Angela Zhai"
date: "30 Sep, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse", "stringr", "varhandle")
```

## Plot
```{r echo=FALSE}
#read excel
import <- read.csv(file = "Imports.csv", header = TRUE, skip = 2, stringsAsFactors=FALSE)
colnames(import) <- c("commodity", "country", "time", "customs_value", "none")
import <- select(import, commodity:customs_value) %>%
  filter(!(time %in% c("2015", "2016", "2017", "2018 through July")) & commodity == "72 Iron And Steel") %>%
  mutate(month = match(word(time, 1, sep = " "), month.name), year = word(time, 2, sep = " ")
         , customs_value = as.numeric(gsub(',', '', customs_value)))
import_sum <- import %>%
  group_by(year, month) %>%
  summarise(value_sum = sum(customs_value))

ggplot(data=import_sum, mapping=(aes(x=month, y=value_sum, color=year))) +
  geom_point() +
  geom_line() +
  scale_y_continuous(name = "Customs Value of Iron and Steel Import", limits = c(0, 250000000)) +
  scale_x_continuous(breaks = import_sum$month) +
  ggtitle("Custom Value of Steel and Steel Import, by Angela Zhai")
```
From the plot above, we can tell that trade war has not affected the metal field so much. Virtually, irons and steels importation value from China in 2015 is extremely high, and some reports also indicated this phenomenon.


